config/routes.rb
Rails.application.routes.draw do

  root "tic_tac_toe#new"

  get '/new' => 'tic_tac_toe#new'
  post '/make_move' => 'tic_tac_toe#make_move'

end

app/models/board.rb
class Board
  attr_reader :board_arr

  def initialize( board_arr = nil )
      @board_arr = board_arr || Board.blank_board
  end

  def self.blank_board
    Array.new( 3 ) { Array.new( 3 ) }
  end

  def add_piece( coordinates, piece )
    @board_arr[ coordinates[0] ][ coordinates[1] ] = piece
  end
  
  def winning_combination?(piece)
    winning_diagonal?(piece)   || 
    winning_horizontal?(piece) || 
    winning_vertical?(piece)
  end

  def winning_diagonal?(piece)
    diagonals.any? do |diag|
      diag.all?{|cell| cell == piece }
    end
  end

  def winning_vertical?(piece)
    verticals.any? do |vert|
      vert.all?{|cell| cell == piece }
    end
  end

  def winning_horizontal?(piece)
    horizontals.any? do |horz|
      horz.all?{|cell| cell == piece }
    end
  end

  def diagonals
    [[ @board_arr[0][0],@board_arr[1][1],@board_arr[2][2] ],[ @board_arr[2][0],@board_arr[1][1],@board_arr[0][2] ]]
  end

  def verticals
    @board_arr
  end

  def horizontals
    horizontals = []
    3.times do |i|
        horizontals << [@board_arr[0][i],@board_arr[1][i],@board_arr[2][i]]
    end
    horizontals
  end

  def full?
    @board_arr.all? do |row|
      row.none?(&:nil?)
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tic_tac_toe_controller.rb
class TicTacToeController < ApplicationController

  def new
    @current_player = 'X'

    @board_arr = Board.new.board_arr

    save_player
    save_board_arr

    render :game_board
  end

  def make_move
    @current_player = retrieve_current_player

    #todo logic for player move

    @board = Board.new( retrieve_board_arr )
    @board.add_piece( retrieve_coordinates, @current_player )

    @board_arr = @board.board_arr

    @game_over = game_over_message

    switch_player
    save_player
    save_board_arr

    render :game_board
  end



  private
  def save_player
    session[ :current_player ] = @current_player  
  end

  def retrieve_current_player
    session[ :current_player ]
  end

  def switch_player
    @current_player = (@current_player == 'X' ? 'O' : 'X')
  end

  def save_board_arr
    session[ :saved_board_arr ] = @board_arr
  end

  def retrieve_board_arr
    session[ :saved_board_arr ]
  end

  def retrieve_coordinates
    params[:move].split(",").map(&:to_i)
  end

  def game_over_message
    if @board.winning_combination?(@current_player)
      @game_over = "Game over, player #{@current_player} WINS!"
    elsif @board.full?
      @game_over = "Game Over! You've drawn."
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tic_tac_toe_helper.rb
module TicTacToeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tic_tac_toe/_ttt_board.html.erb
<pre>
  <table>
    <% board_arr.each do |row| %>
      <tr> 
        <% row.each do |cell| %>
          <td>
            <%= cell.nil? ? '-' : cell %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</pre>

app/views/tic_tac_toe/_ttt_form.html.erb
<%= form_tag( make_move_path, :method => "POST" ) do %>
  <table>
    <% 3.times do |row| %>
      <tr> 
        <% 3.times do |cell| %>
          <td>
            <% disabled = board_arr[row][cell] %>
            <%= radio_button_tag( "move",
                  "#{row},#{cell}",
                  !disabled,
                  :disabled => disabled) 
            %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= submit_tag "Make Move" %>
<% end %>

app/views/tic_tac_toe/_ttt_header.html.erb
<% if game_over %>
  <h2>
    <%= "#{game_over}" %>
  </h2>
<% else %>
  <h2>
    It is player <%= "#{current_player}" %>'s turn!
  </h2>

  <p>
    Enter your selection using the form below
  </p>
<% end %>

app/views/tic_tac_toe/game_board.html.erb
<h1>Welcome to TicTacToe!</h1>

<%=  render :partial => "ttt_header", :locals => { :current_player => @current_player, :game_over => @game_over } %>

<%= render :partial => "ttt_board", :locals => { :board_arr => @board_arr } %>


<% if @game_over %>  
  <%= link_to "Play Again!", new_path %>
<% else %>
  <%= render :partial => "ttt_form", :locals => { :board_arr => @board_arr } %>
<% end %>